# Site settings
title: "CSC 311 Project Blog" 
name: "Anthony DeDominic"
email: anthony@dedominic.pw
description: > # this means to ignore newlines until "baseurl:"
    Blog about development of school project for CSC 311
baseurl: "/CSC311-game-design" # the subpath of your site, e.g. /blog/
url: "https://adedomin.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: adedomin

# Build settings
markdown: kramdown
