# Site settings
title: CSC 311 - Game Design Project
email: anthony@dedominic.pw
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://adedomin.github.io/CSC311-game-design/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  adedomin

# Build settings
markdown: kramdown
